# Generated by Django 4.2.7 on 2025-11-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abtesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Algorithm Performance Test', max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('svd', 'SVD Matrix Factorization'), ('content', 'Content-Based'), ('hybrid', 'Hybrid Approach')], max_length=20)),
                ('num_recommendations', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('response_time', models.FloatField(default=0.0)),
                ('diversity_score', models.FloatField(default=0.0)),
                ('user_satisfaction', models.IntegerField(default=0)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abtesting.algorithmcomparison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
